import {
  faAddressBook,
  faAddressCard,
  faArrowLeft,
  faArrowRight,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faBox,
  faBriefcase,
  faBusinessTime,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDay,
  faCalendarPlus,
  faCalendarTimes,
  faCar,
  faCheck,
  faCheckCircle,
  faCheckDouble,
  faCheckSquare,
  faChevronLeft,
  faChevronRight,
  faChild,
  faClock,
  faCloud,
  faCloudShowersHeavy,
  faCopy,
  faCut,
  faDownload,
  faExclamation,
  faExclamationCircle,
  faExternalLinkSquareAlt,
  faEye,
  faEyeSlash,
  faFile,
  faFileAlt,
  faFileCsv,
  faFileExcel,
  faFileInvoiceDollar,
  faFilePdf,
  faFilePowerpoint,
  faFileSignature,
  faFileWord,
  faFistRaised,
  faFlag,
  faFolder,
  faGift,
  faHandHoldingWater,
  faHandSpock,
  faHdd,
  faHeart,
  faHome,
  faIdCard,
  faInfoCircle,
  faKey,
  faLaptopHouse,
  faList,
  faLocationArrow,
  faLock,
  faLockOpen,
  faMapMarkedAlt,
  faMinusCircle,
  faMoneyCheckAlt,
  faPauseCircle,
  faPencilAlt,
  faPhoneAlt,
  faPlaneDeparture,
  faPlus,
  faPlusSquare,
  faPrint,
  faProcedures,
  faProjectDiagram,
  faQuestion,
  faRedo,
  faRoad,
  faSave,
  faSearch,
  faSignInAlt,
  faSignOutAlt,
  faSmileBeam,
  faSort,
  faSortDown,
  faSortUp,
  faSpinner,
  faStethoscope,
  faSwimmer,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTimesCircle,
  faTint,
  faToggleOff,
  faToggleOn,
  faTrash,
  faTrashAlt,
  faUmbrellaBeach,
  faUser,
  faUserAlt,
  faUserAltSlash,
  faUserAstronaut,
  faUserCheck,
  faUserCircle,
  faUserClock,
  faUserCog,
  faUserEdit,
  faUserFriends,
  faUserGraduate,
  faUserInjured,
  faUserLock,
  faUserMd,
  faUserMinus,
  faUserNinja,
  faUserNurse,
  faUserPlus,
  faUsers,
  faUsersCog,
  faUserSecret,
  faUserShield,
  faUserSlash,
  faUsersSlash,
  faUserTag,
  faUserTie,
  faUserTimes,
  faWater,
  faWrench,
  faGlobe,
  faIdCardAlt,
  faMagic,
  faFingerprint,
  faDesktop,
  faUpload
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeIcons = [
  // faArrowLeft,
  // faAsterisk,
  // faBan,
  // faBars,
  // faBell,
  // faBook,
  // faCalendarAlt,
  // faCheck,
  // faCloud,
  // faCogs,
  // faDatabase,
  // faEye,
  // faFlag,
  // faHeart,
  // faHome,
  // faList,
  // faLock,
  // faPencilAlt,
  // faPlus,
  // faRoad,
  // faSave,
  // faSearch,
  // faSignOutAlt,
  // faSignInAlt,
  // faSort,
  // faSortDown,
  // faSortUp,
  // faSync,
  // faTachometerAlt,
  // faTasks,
  // faThList,
  // faTimes,
  // faTrashAlt,
  // faUser,
  // faUserPlus,
  // faUsers,
  // faUsersCog,
  // faWrench,
  // jhipster-needle-add-icon-import

  faUser,
  faUserAlt,
  faUserAltSlash,
  faUserAstronaut,
  faUserCheck,
  faUserCircle,
  faUserClock,
  faUserCog,
  faUserEdit,
  faUserFriends,
  faUserGraduate,
  faUserInjured,
  faUserLock,
  faUserMd,
  faUserMinus,
  faUserNinja,
  faUserNurse,
  faUserPlus,
  faUserSecret,
  faUserShield,
  faUserSlash,
  faUserTag,
  faUserTie,
  faUserTimes,
  faUsers,
  faUsersCog,
  faUsersSlash,
  faSort,
  faSortUp,
  faSortDown,
  faSync,
  faEye,
  faEyeSlash,
  faBan,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faSave,
  faPlus,
  faPencilAlt,
  faBars,
  faHome,
  faThList,
  faUserPlus,
  faRoad,
  faTachometerAlt,
  faHeart,
  faProcedures,
  faList,
  faBell,
  faTasks,
  faBook,
  faHdd,
  faFlag,
  faWrench,
  faLock,
  faCloud,
  faSignOutAlt,
  faSignInAlt,
  faCalendarAlt,
  faCalendarTimes,

  faSearch,
  faTrashAlt,
  faHandSpock,
  // jhipster-needle-add-icon-import
  faAsterisk,
  faCheckCircle,
  faCheckSquare,
  faCheckDouble,
  faSmileBeam,
  faHandHoldingWater,
  faWater,
  faTint,
  faToggleOff,
  faToggleOn,
  faUmbrellaBeach,
  faAddressBook,
  faGift,
  faChevronLeft,
  faChevronRight,
  faInfoCircle,
  faCheck,
  faClock,
  faExclamation,
  faExclamationCircle,
  faPlusSquare,
  faBusinessTime,
  faAddressCard,
  faMoneyCheckAlt,
  faFile,
  faFileAlt,
  faUserCheck,
  faUserClock,
  faFileInvoiceDollar,
  faFolder,
  faCalendar,
  faCalendarDay,
  faCalendarPlus,
  faCalendarCheck,
  faCalendarTimes,

  faSwimmer,
  faPrint,
  faDownload,
  faLockOpen,
  faSpinner,
  faPauseCircle,
  faCopy,
  faQuestion,
  faLocationArrow,
  faUserPlus,
  faCloudShowersHeavy,
  faBox,
  faMapMarkedAlt,
  faChild,
  faIdCard,
  faRedo,
  faProjectDiagram,
  faFileSignature,
  faExternalLinkSquareAlt,
  faCar,
  faBriefcase,
  faPlaneDeparture,
  faStethoscope,
  faKey,
  faMinusCircle,
  faFileCsv,
  faFileExcel,
  faFistRaised,
  faFilePdf,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faTimesCircle,
  faLaptopHouse,
  faCut,
  faTrash,
  faPhoneAlt,
  faGlobe,
  faIdCardAlt,
  faMagic,
  faFingerprint,
  faDesktop,
  faUpload
];
