ROLE_USER:
  - COMMON
  - EMPLOYEE_MANAGEMENT_READ

ROLE_ADMIN:
  - EMPLOYEE_MANAGEMENT
  - ATTENDANCE_MANAGEMENT
  - PF_MANAGEMENT
  - PAYROLL_MANAGEMENT
  - AIT_MANAGEMENT
  - AUTHORITY_MANAGEMENT
  - ADMINISTRATION
  - USER_MANAGEMENT

ROLE_PROCUREMENT_OFFICER:
  - PROCUREMENT_MANAGEMENT
