export enum EmployeeCategory {
  REGULAR_CONFIRMED_EMPLOYEE = 'REGULAR_CONFIRMED_EMPLOYEE',

  REGULAR_PROVISIONAL_EMPLOYEE = 'REGULAR_PROVISIONAL_EMPLOYEE',

  CONTRACTUAL_EMPLOYEE = 'CONTRACTUAL_EMPLOYEE',

  INTERN = 'INTERN',
}
