export const enum NomineeStatus {
  APPROVED = 'APPROVED',
  ALL_APPROVED = 'ALL_APPROVED',
  PARTIAL_APPROVED = 'PARTIAL_APPROVED',
  NOT_APPROVED = 'NOT_APPROVED',
  NOT_ELIGIBLE = 'NOT_ELIGIBLE',
  INCOMPLETE = 'INCOMPLETE',
  PENDING = 'PENDING',
}
