import dayjs from 'dayjs/esm';
import { EmployeeCategory } from '../../shared/model/enumerations/employee-category.model';

export interface IFinalSettlement {
  id: number;
  dateOfResignation?: dayjs.Dayjs | null;
  noticePeriod?: number | null;
  lastWorkingDay?: dayjs.Dayjs | null;
  dateOfRelease?: dayjs.Dayjs | null;
  serviceTenure?: string | null;
  mBasic?: number | null;
  mHouseRent?: number | null;
  mMedical?: number | null;
  mConveyance?: number | null;
  salaryPayable?: number | null;
  salaryPayableRemarks?: string | null;
  totalDaysForLeaveEncashment?: number | null;
  totalLeaveEncashment?: number | null;
  mobileBillInCash?: number | null;
  allowance01Name?: string | null;
  allowance01Amount?: number | null;
  allowance01Remarks?: string | null;
  allowance02Name?: string | null;
  allowance02Amount?: number | null;
  allowance02Remarks?: string | null;
  allowance03Name?: string | null;
  allowance03Amount?: number | null;
  allowance03Remarks?: string | null;
  allowance04Name?: string | null;
  allowance04Amount?: number | null;
  allowance04Remarks?: string | null;
  deductionNoticePay?: number | null;
  deductionPf?: number | null;
  deductionHaf?: number | null;
  deductionExcessCellBill?: number | null;
  deductionAbsentDaysAdjustment?: number | null;
  totalSalaryPayable?: number | null;
  deductionAnnualIncomeTax?: number | null;
  netSalaryPayable?: number | null;
  totalPayablePf?: number | null;
  totalPayableGf?: number | null;
  totalFinalSettlementAmount?: number | null;
  createdAt?: dayjs.Dayjs | null;
  updatedAt?: dayjs.Dayjs | null;
  deductionNoticePayDays?: number | null;
  deductionAbsentDaysAdjustmentDays?: number | null;
  deductionOther?: number | null;
  totalSalary?: number | null;
  totalGrossSalary?: number | null;
  totalDeduction?: number | null;
  finalSettlementDate?: dayjs.Dayjs | null;
  isFinalized?: boolean | null;
  salaryNumOfMonth?: number | null;
  remarks?: string | null;
  employeeId?: number;
  employeeFullName?: string;
  employeePin?: string;
  dateOfJoining?: dayjs.Dayjs;
  dateOfConfirmation?: dayjs.Dayjs;
  employeeCategory?: EmployeeCategory;
  createdByLogin?: string;
  createdById?: number;
  updatedByLogin?: string;
  updatedById?: number;

  // employee?: Pick<IEmployee, 'id'> | null;
  // createdBy?: Pick<IUser, 'id' | 'login'> | null;
  // updatedBy?: Pick<IUser, 'id' | 'login'> | null;
}

export type NewFinalSettlement = Omit<IFinalSettlement, 'id'> & { id: null };
