import dayjs from 'dayjs/esm';

import { BloodGroup } from 'app/entities/enumerations/blood-group.model';
import { Religion } from 'app/entities/enumerations/religion.model';
import { MaritalStatus } from 'app/entities/enumerations/marital-status.model';
import { EmployeeCategory } from 'app/entities/enumerations/employee-category.model';
import { PayType } from 'app/entities/enumerations/pay-type.model';
import { DisbursementMethod } from 'app/entities/enumerations/disbursement-method.model';
import { CardType } from 'app/entities/enumerations/card-type.model';
import { Gender } from 'app/entities/enumerations/gender.model';
import { EmploymentStatus } from 'app/entities/enumerations/employment-status.model';

import { IEmployee, NewEmployee } from './employee.model';

export const sampleWithRequiredData: IEmployee = {
  id: 7813,
  pin: 'transmitting',
};

export const sampleWithPartialData: IEmployee = {
  id: 17628,
  referenceId: 'Virginia Senior',
  pin: 'metrics Loan Brand',
  fullName: 'Wooden Planner',
  surName: 'circuit',
  nationalIdNo: 'grey Home EXE',
  dateOfBirth: dayjs('2021-02-15'),
  fatherName: 'Engineer quantifying',
  personalContactNo: 'synergistic Product Botswana',
  personalEmail: 'Technician Computer',
  dateOfMarriage: dayjs('2021-02-15'),
  officialContactNo: 'Steel Wisconsin',
  whatsappId: 'overriding Baby',
  emergencyContactPersonRelationshipWithEmployee: 'transmitting Creative',
  location: 'communities',
  isProbationaryPeriodExtended: true,
  payType: PayType['UNPAID'],
  disbursementMethod: DisbursementMethod['CASH'],
  bankName: 'primary quantifying',
  mobileCelling: 18441,
  bkashNumber: 'Intelligent virtual',
  cardType: CardType['CREDIT_CARD'],
  passportNo: 'Islands Fresh Florida',
  passportPlaceOfIssue: 'white Account Representative',
  gender: Gender['FEMALE'],
  employmentStatus: EmploymentStatus['ACTIVE'],
  hasDisabledChild: false,
  isFestivalBonusHold: false,
  isPhysicallyDisabled: true,
  isFreedomFighter: false,
  hasOverTime: false,
  contractPeriodEndDate: dayjs('2021-02-14'),
  cardType02: CardType['CREDIT_CARD'],
  allowance01EffectiveFrom: dayjs('2021-02-15'),
  allowance02: 4745130,
  allowance02EffectiveFrom: dayjs('2021-02-14'),
  allowance02EffectiveTo: dayjs('2021-02-15'),
  allowance03EffectiveFrom: dayjs('2021-02-15'),
  allowance03EffectiveTo: dayjs('2021-02-14'),
  allowance04: 3018176,
  allowance04EffectiveFrom: dayjs('2021-02-15'),
  createdBy: 'Lead synthesizing',
  createdAt: dayjs('2021-02-15T06:34'),
  updatedBy: 'SSL Yemen',
  isAllowedToGiveOnlineAttendance: false,
  noticePeriodInDays: 98364,
  isFixedTermContract: false,
  currentOutTime: dayjs('2021-02-14T13:19'),
  taxesCircle: 'American',
  canManageTaxAcknowledgementReceipt: false,
  isAugmentedResource: false,
  lastWorkingDay: dayjs('2021-02-14'),
};

export const sampleWithFullData: IEmployee = {
  id: 38467,
  referenceId: 'bandwidth Concrete US',
  pin: 'hack',
  picture: 'Manager',
  fullName: 'expedite Pants',
  surName: 'Wooden',
  nationalIdNo: 'Washington Arizona',
  dateOfBirth: dayjs('2021-02-15'),
  placeOfBirth: 'View',
  fatherName: 'monitor',
  motherName: 'Synergistic',
  bloodGroup: BloodGroup['A_POSITIVE'],
  presentAddress: 'Turkish Michigan',
  permanentAddress: 'Utah Netherlands Handcrafted',
  personalContactNo: 'implementation digital',
  personalEmail: 'Engineer optimizing',
  religion: Religion['CHRISTIAN'],
  maritalStatus: MaritalStatus['MARRIED'],
  dateOfMarriage: dayjs('2021-02-15'),
  spouseName: 'Jewelery Handmade',
  officialEmail: 'Awesome Avon GB',
  officialContactNo: 'Forward Salad relationships',
  officePhoneExtension: 'PNG end-to-end Response',
  whatsappId: 'Small',
  skypeId: 'deposit',
  emergencyContactPersonName: 'architect',
  emergencyContactPersonRelationshipWithEmployee: 'array',
  emergencyContactPersonContactNumber: 'override',
  mainGrossSalary: 50551,
  employeeCategory: EmployeeCategory['INTERN'],
  location: 'synthesizing',
  dateOfJoining: dayjs('2021-02-14'),
  dateOfConfirmation: dayjs('2021-02-14'),
  isProbationaryPeriodExtended: false,
  probationPeriodExtendedTo: dayjs('2021-02-14'),
  payType: PayType['MONTHLY'],
  disbursementMethod: DisbursementMethod['MOBILE_BANKING'],
  bankName: 'mesh disintermediate',
  bankAccountNo: '24/7 next-generation overriding',
  mobileCelling: 97566,
  bkashNumber: 'metrics up Cheese',
  cardType: CardType['DEBIT_CARD'],
  cardNumber: 'Human Directives',
  tinNumber: 'Cross-platform Zambian',
  passportNo: 'Interface',
  passportPlaceOfIssue: 'Agent',
  passportIssuedDate: dayjs('2021-02-14'),
  passportExpiryDate: dayjs('2021-02-15'),
  gender: Gender['OTHER'],
  welfareFundDeduction: 47737,
  employmentStatus: EmploymentStatus['RESIGNED'],
  hasDisabledChild: true,
  isFirstTimeAitGiver: true,
  isSalaryHold: false,
  isFestivalBonusHold: true,
  isPhysicallyDisabled: true,
  isFreedomFighter: false,
  hasOverTime: false,
  probationPeriodEndDate: dayjs('2021-02-15'),
  contractPeriodExtendedTo: dayjs('2021-02-14'),
  contractPeriodEndDate: dayjs('2021-02-14'),
  cardType02: CardType['CREDIT_CARD'],
  cardNumber02: 'withdrawal Path',
  cardType03: CardType['DEBIT_CARD'],
  cardNumber03: 'niches Plastic',
  allowance01: 9452973,
  allowance01EffectiveFrom: dayjs('2021-02-15'),
  allowance01EffectiveTo: dayjs('2021-02-14'),
  allowance02: 9459426,
  allowance02EffectiveFrom: dayjs('2021-02-15'),
  allowance02EffectiveTo: dayjs('2021-02-15'),
  allowance03: 5512826,
  allowance03EffectiveFrom: dayjs('2021-02-15'),
  allowance03EffectiveTo: dayjs('2021-02-14'),
  allowance04: 1717712,
  allowance04EffectiveFrom: dayjs('2021-02-14'),
  allowance04EffectiveTo: dayjs('2021-02-14'),
  allowance05: 6328940,
  allowance05EffectiveFrom: dayjs('2021-02-14'),
  allowance05EffectiveTo: dayjs('2021-02-14'),
  allowance06: 6968389,
  allowance06EffectiveFrom: dayjs('2021-02-14'),
  allowance06EffectiveTo: dayjs('2021-02-14'),
  isTaxPaidByOrganisation: false,
  createdBy: 'Granite Berkshire Circles',
  createdAt: dayjs('2021-02-14T16:29'),
  updatedBy: 'throughput orange Senior',
  updatedAt: dayjs('2021-02-14'),
  isAllowedToGiveOnlineAttendance: true,
  noticePeriodInDays: 80957,
  isFixedTermContract: true,
  currentInTime: dayjs('2021-02-14T22:44'),
  currentOutTime: dayjs('2021-02-15T04:39'),
  onlineAttendanceSanctionedAt: dayjs('2021-02-15T05:40'),
  isNidVerified: true,
  canRaiseRrfOnBehalf: false,
  taxesCircle: 'system Pennsylvania Light',
  taxesZone: 'Configuration',
  canManageTaxAcknowledgementReceipt: true,
  isEligibleForAutomatedAttendance: false,
  floor: 'Incredible',
  deskLocation: 'program',
  isBillableResource: false,
  isAugmentedResource: false,
  lastWorkingDay: dayjs('2021-02-15'),
};

export const sampleWithNewData: NewEmployee = {
  pin: 'heuristic copy',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
