ALTER TABLE EMPLOYEE_SALARY
    ADD COLUMN TITLE                    VARCHAR(255),
    ADD COLUMN IS_VISIBLE_TO_EMPLOYEE   BOOLEAN,
    ADD COLUMN PF_ARREAR                DOUBLE precision,
    ADD COLUMN TAX_CALCULATION_SNAPSHOT TEXT;
