create table if not exists MANUAL_ATTENDANCE_ENTRY
(
    ID BIGINT not null,
    DATE DATE,
    IN_TIME TIMESTAMP default NULL,
    IN_NOTE VARCHAR(255),
    OUT_TIME TIMESTAMP default NULL,
    OUT_NOTE VARCHAR(255),
    IS_LINE_MANAGER_APPROVED BOOLEAN,
    IS_HR_APPROVED BOOLEAN,
    IS_REJECTED BOOLEAN,
    REJECTION_COMMENT VARCHAR(255),
    EMPLOYEE_ID BIGINT,
    constraint PK_MANUAL_ATTENDANCE_ENTRY
        primary key (ID),
    constraint FK_MANUAL_ATTENDANCE_ENTRY_EMPLOYEE_ID
        foreign key (EMPLOYEE_ID) references EMPLOYEE (ID)
);
