ALTER TABLE  PF_ACCOUNT
    DROP CONSTRAINT FK_PF_ACCOUNT_EMPLOYEE_ID;

ALTER TABLE PF_ACCOUNT
    ADD COLUMN PIN VARCHAR(255),
    ADD COLUMN ACC_HOLDER_NAME VARCHAR(255),
    ADD COLUMN DESIGNATION_NAME VARCHAR(255),
    ADD COLUMN DEPARTMENT_NAME VARCHAR(255),
    ADD COLUMN UNIT_NAME VARCHAR(255);

ALTER TABLE PF_COLLECTION
    ADD COLUMN EMPLOYEE_INTEREST DOUBLE PRECISION DEFAULT 0,
    ADD COLUMN EMPLOYER_INTEREST DOUBLE PRECISION DEFAULT 0;

ALTER TABLE PF_LOAN_APPLICATION
    RENAME COLUMN DIBRUSHMENT_AMOUNT TO DISBURSEMENT_AMOUNT;

ALTER TABLE PF_LOAN_APPLICATION
    RENAME COLUMN DIBRUSHMENT_DATE TO DISBURSEMENT_DATE;

ALTER TABLE PF_LOAN_APPLICATION
    ADD COLUMN STATUS VARCHAR(255);

ALTER TABLE EMPLOYEE_RESIGNATION
    RENAME COLUMN RESIGNATION_DATE TO LAST_WORKING_DAY;

ALTER TABLE EMPLOYEE_RESIGNATION
    ADD COLUMN RESIGNATION_DATE DATE;

ALTER TABLE EMPLOYEE
    ADD COLUMN NOTICE_PERIOD_IN_DAYS INTEGER ;




