CREATE TABLE IF NOT EXISTS FILE_TEMPLATES
(
    ID               BIGINT       NOT NULL,
    TITLE            VARCHAR(250) NOT NULL
        CONSTRAINT UX_FILE_TEMPLATES_TITLE
            UNIQUE,
    FILE_PATH        TEXT,
    TYPE             VARCHAR(255),
    ACCESS_PRIVILEGE VARCHAR(255),
    IS_ACTIVE        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_FILE_TEMPLATES
        PRIMARY KEY (ID)
);

