ALTER TABLE ATTENDANCE_SUMMARY
    ADD COLUMN ATTENDANCE_REGULARISATION_START_DATE date,
    ADD COLUMN ATTENDANCE_REGULARISATION_END_DATE   date;

ALTER TABLE EMPLOYEE_SALARY
    ADD COLUMN ATTENDANCE_REGULARISATION_START_DATE date,
    ADD COLUMN ATTENDANCE_REGULARISATION_END_DATE   date;
