ALTER TABLE RECRUITMENT_REQUISITION_FORM
    ADD COLUMN REQUESTER_ID BIGINT;

ALTER TABLE RECRUITMENT_REQUISITION_FORM
    ADD CONSTRAINT FK_RECRUITMENT_REQUISITION_FORM_REQUESTER_ID
        FOREIGN KEY (REQUESTER_ID) REFERENCES EMPLOYEE (ID);
