create table IF NOT EXISTS FINAL_SETTLEMENT
(
    ID                                    BIGINT not null,
    DATE_OF_RESIGNATION                   DATE,
    NOTICE_PERIOD                         INT,
    LAST_WORKING_DAY                      DATE,
    DATE_OF_RELEASE                       DATE,
    SERVICE_TENURE                        VARCHAR(255),
    M_BASIC                               DOUBLE PRECISION ,
    M_HOUSE_RENT                          DOUBLE PRECISION ,
    M_MEDICAL                             DOUBLE PRECISION ,
    M_CONVEYANCE                          DOUBLE PRECISION ,
    SALARY_PAYABLE                        DOUBLE PRECISION ,
    SALARY_PAYABLE_REMARKS                VARCHAR(255),
    TOTAL_DAYS_FOR_LEAVE_ENCASHMENT       DOUBLE PRECISION ,
    TOTAL_LEAVE_ENCASHMENT                DOUBLE PRECISION ,
    MOBILE_BILL_IN_CASH                   DOUBLE PRECISION ,
    ALLOWANCE_01_NAME                     VARCHAR(255),
    ALLOWANCE_01_AMOUNT                   DOUBLE PRECISION ,
    ALLOWANCE_01_REMARKS                  VARCHAR(255),
    ALLOWANCE_02_NAME                     VARCHAR(255),
    ALLOWANCE_02_AMOUNT                   DOUBLE PRECISION ,
    ALLOWANCE_02_REMARKS                  VARCHAR(255),
    ALLOWANCE_03_NAME                     VARCHAR(255),
    ALLOWANCE_03_AMOUNT                   DOUBLE PRECISION ,
    ALLOWANCE_03_REMARKS                  VARCHAR(255),
    ALLOWANCE_04_NAME                     VARCHAR(255),
    ALLOWANCE_04_AMOUNT                   DOUBLE PRECISION ,
    ALLOWANCE_04_REMARKS                  VARCHAR(255),
    DEDUCTION_NOTICE_PAY                  DOUBLE PRECISION ,
    DEDUCTION_PF                          DOUBLE PRECISION ,
    DEDUCTION_HAF                         DOUBLE PRECISION ,
    DEDUCTION_EXCESS_CELL_BILL            DOUBLE PRECISION ,
    DEDUCTION_ABSENT_DAYS_ADJUSTMENT      DOUBLE PRECISION ,
    TOTAL_SALARY_PAYABLE                  DOUBLE PRECISION ,
    DEDUCTION_ANNUAL_INCOME_TAX           DOUBLE PRECISION ,
    NET_SALARY_PAYABLE                    DOUBLE PRECISION ,
    TOTAL_PAYABLE_PF                      DOUBLE PRECISION ,
    TOTAL_PAYABLE_GF                      DOUBLE PRECISION ,
    TOTAL_FINAL_SETTLEMENT_AMOUNT         DOUBLE PRECISION ,
    CREATED_AT                            DATE,
    UPDATED_AT                            DATE,
    DEDUCTION_NOTICE_PAY_DAYS             INT,
    DEDUCTION_ABSENT_DAYS_ADJUSTMENT_DAYS INT,
    DEDUCTION_OTHER                       DOUBLE PRECISION ,
    TOTAL_SALARY                          DOUBLE PRECISION ,
    TOTAL_GROSS_SALARY                    DOUBLE PRECISION ,
    TOTAL_DEDUCTION                       DOUBLE PRECISION ,
    FINAL_SETTLEMENT_DATE                 DATE,
    EMPLOYEE_ID                           BIGINT not null,
    CREATED_BY_ID                         BIGINT,
    UPDATED_BY_ID                         BIGINT,
    constraint PK_FINAL_SETTLEMENT
        primary key (ID),
    constraint FK_FINAL_SETTLEMENT_CREATED_BY_ID
        foreign key (CREATED_BY_ID) references JHI_USER (ID),
    constraint FK_FINAL_SETTLEMENT_EMPLOYEE_ID
        foreign key (EMPLOYEE_ID) references EMPLOYEE (ID),
    constraint FK_FINAL_SETTLEMENT_UPDATED_BY_ID
        foreign key (UPDATED_BY_ID) references JHI_USER (ID)
);
